@startuml
'https://plantuml.com/sequence-diagram

Client -> TeamController: HTTP PUT /teams/:id
activate TeamController
TeamController -> TeamService: updateTeam(id : String, team: UpdateTeamDTO)

activate TeamService
TeamService -> BusinessTeam: validateToUpdate()
activate BusinessTeam
deactivate BusinessTeam
TeamService -> TeamModel: updateTeam(id: String, team : BusinessTeam)

activate TeamModel
TeamModel -> TeamRepository: findById(id : String)
activate TeamRepository
TeamModel <-- TeamRepository: Team?
deactivate TeamRepository
TeamModel -> TeamRepository: save(Team)
activate TeamRepository
TeamModel <-- TeamRepository: Team
deactivate TeamRepository
deactivate TeamModel

deactivate TeamService

Client <-- TeamController: response: HTTP 200 OK
deactivate TeamController

@enduml